### ISSUE TITLE
Stats not measured if below a certain count

### ISSUE THREAD

**Issue by binarytemple** [basho/basho_stats#5]
Hi,

https://basho.zendesk.com/agent/tickets/9258

We observed a number of quantile stats at zero, even though there is a small amount of activity:

```
node_get_fsm_time_mean 0 1414405501
node_get_fsm_time_median 0 1414405501
node_get_fsm_time_95 0 1414405501
node_get_fsm_time_99 0 1414405501
node_get_fsm_time_100 0 1414405501
node_put_fsm_time_mean 0 1414405501
node_put_fsm_time_median 0 1414405501
node_put_fsm_time_95 0 1414405501
node_put_fsm_time_99 0 1414405501
node_put_fsm_time_100 0 1414405501
vnode_gets.count 3 1414405501
vnode_puts.count 1 1414405501
read_repairs.count 0 1414405501
node_gets.count 1 1414405501
node_puts.count 1 1414405501
pbc_connects.count 0 1414405501
```

Further investigation shows a threshold in the [source code](https://github.com/basho/basho_stats/blob/develop/src/basho_stats_histogram.erl#L237,L261) below which statistics are not measured. 

Is it the case that less than 50 items per minute are disregarded by the `time_mean`/ `time_median`/ `time_9x` metrics ?

Bryan

**Comment by bsparrow435** [comment]
Currently, we have no plans to change this behavior as we've moved off this stats system for our primary stats engine. Thanks as always!
